services:
  - type: web
    name: repo-impact-rag-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn backend.api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: GROQ_API_KEY
        sync: false
      - key: gh_token
        sync: false
    autoDeploy: true